// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Production Firebase configuration - replace with your actual project
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your-web-api-key-here',
    appId: 'your-web-app-id-here',
    messagingSenderId: 'your-sender-id-here',
    projectId: 'homelink-ghana-production',
    authDomain: 'homelink-ghana-production.firebaseapp.com',
    storageBucket: 'homelink-ghana-production.appspot.com',
  );

  // Production Firebase configuration - replace with your actual project
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'your-android-api-key-here',
    appId: 'your-android-app-id-here',
    messagingSenderId: 'your-sender-id-here',
    projectId: 'homelink-ghana-production',
    storageBucket: 'homelink-ghana-production.appspot.com',
  );

  // Production Firebase configuration - replace with your actual project
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your-ios-api-key-here',
    appId: 'your-ios-app-id-here',
    messagingSenderId: 'your-sender-id-here',
    projectId: 'homelink-ghana-production',
    storageBucket: 'homelink-ghana-production.appspot.com',
    iosBundleId: 'com.homelink.provider.app',
  );
}