// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // SECURITY NOTE: These are PLACEHOLDER/EXAMPLE values for development
  // Replace with actual Firebase project credentials for production
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6D7E8F9G0H1I2J3K4L5M6N7O8P9Q0R1S', // PLACEHOLDER - Replace with real key
    appId: '1:234567890123:web:a1b2c3d4e5f6g7h8i9j0k1l2', // PLACEHOLDER - Replace with real app ID
    messagingSenderId: '234567890123', // PLACEHOLDER - Replace with real sender ID
    projectId: 'homelink-ghana-provider', // PLACEHOLDER - Replace with real project ID
    authDomain: 'homelink-ghana-provider.firebaseapp.com',
    storageBucket: 'homelink-ghana-provider.appspot.com',
  );

  // SECURITY NOTE: These are PLACEHOLDER/EXAMPLE values for development
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6D7E8F9G0H1I2J3K4L5M6N7O8P9Q0R1S', // PLACEHOLDER - Replace with real key
    appId: '1:234567890123:android:2b3c4d5e6f7g8h9i', // PLACEHOLDER - Replace with real app ID
    messagingSenderId: '234567890123', // PLACEHOLDER - Replace with real sender ID
    projectId: 'homelink-ghana-provider', // PLACEHOLDER - Replace with real project ID
    storageBucket: 'homelink-ghana-provider.appspot.com',
  );

  // SECURITY NOTE: These are PLACEHOLDER/EXAMPLE values for development
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDifferentKeyForIOS123456789', // PLACEHOLDER - Replace with real iOS key
    appId: '1:234567890123:ios:1a2b3c4d5e6f7g8h', // PLACEHOLDER - Replace with real iOS app ID
    messagingSenderId: '234567890123', // PLACEHOLDER - Replace with real sender ID
    projectId: 'homelink-ghana-provider', // PLACEHOLDER - Replace with real project ID
    storageBucket: 'homelink-ghana-provider.appspot.com',
    iosBundleId: 'com.homelink.provider.app',
  );
}