# iOS compatible deployment target  
platform :ios, '14.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      
      # Fix Firebase/gRPC compilation issues
      config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
      config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
      
      # Fix for Firebase, gRPC, and BoringSSL compilation issues
      if target.name.include?('Firebase') || target.name.include?('abseil') || target.name.include?('gRPC') || target.name.include?('BoringSSL')
        config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
        config.build_settings['CLANG_WARN_STRICT_PROTOTYPES'] = 'NO'
        config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
        config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
        config.build_settings['CLANG_WARN_UNGUARDED_AVAILABILITY'] = 'NO'
        config.build_settings['CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS'] = 'NO'
        config.build_settings['CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF'] = 'NO'
        config.build_settings['GCC_WARN_64_TO_32_BIT_CONVERSION'] = 'NO'
        config.build_settings['GCC_WARN_ABOUT_RETURN_TYPE'] = 'NO'
        config.build_settings['GCC_WARN_UNDECLARED_SELECTOR'] = 'NO'
        config.build_settings['GCC_WARN_UNINITIALIZED_AUTOS'] = 'NO'
        config.build_settings['GCC_WARN_UNUSED_FUNCTION'] = 'NO'
        config.build_settings['GCC_WARN_UNUSED_VARIABLE'] = 'NO'
        
        # Fix for BoringSSL-GRPC compilation errors
        config.build_settings['GCC_OPTIMIZATION_LEVEL'] = '0'
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
        
        # Remove problematic debug flags for BoringSSL
        config.build_settings.delete('DEBUG_INFORMATION_FORMAT')
        config.build_settings.delete('GCC_GENERATE_DEBUGGING_SYMBOLS')
        
        # Force C++ standard
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
      end
      
      # Specific fixes for problematic targets
      if target.name == 'FirebaseFirestoreInternal'
        config.build_settings['HEADER_SEARCH_PATHS'] = [
          '$(inherited)',
          '"${PODS_ROOT}/abseil"',
          '"${PODS_ROOT}/gRPC-Core"',
          '"${PODS_ROOT}/gRPC-C++"',
        ]
      end
      
      if target.name.include?('BoringSSL') || target.name.include?('openssl')
        config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
      end
      
      # Remove problematic flags that cause compilation errors
      config.build_settings.delete('WARNING_CFLAGS')
      config.build_settings.delete('GCC_PREPROCESSOR_DEFINITIONS')
      config.build_settings.delete('OTHER_CPLUSPLUSFLAGS')
      config.build_settings.delete('OTHER_CFLAGS')
      
      # Fix the specific -G flag issue for BoringSSL-GRPC
      if target.name.include?('BoringSSL-GRPC')
        config.build_settings['GCC_OPTIMIZATION_LEVEL'] = 's'
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-O'
        config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
        config.build_settings['GCC_GENERATE_DEBUGGING_SYMBOLS'] = 'NO'
        
        # Remove all debug-related flags that might include -G
        config.build_settings.delete('GCC_DEBUGGING_SYMBOLS')
        config.build_settings.delete('LLVM_LTO')
        config.build_settings.delete('OTHER_CFLAGS')
        config.build_settings.delete('OTHER_CPLUSPLUSFLAGS')
      end
    end
  end
end